### ISSUE TITLE
Decoding of scalar null values fails

### ISSUE THREAD

**Issue by mp911de** [r2dbc/r2dbc-h2#166]
#### Versions

- Driver: 0.8.4.RELEASE
- Database:
- Java:
- OS:

#### Current Behavior

```
java.lang.IllegalArgumentException: Cannot decode value of type java.lang.String
		at io.r2dbc.h2.codecs.DefaultCodecs.decode(DefaultCodecs.java:60)
		at io.r2dbc.h2.H2Row.get(H2Row.java:66)
		at io.r2dbc.h2.H2RowTest.lambda$nullDecode$4(H2RowTest.java:110)
		at io.r2dbc.h2.H2Result.lambda$map$0(H2Result.java:67)
		at reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:100)
```
 
#### Table schema

```
CREATE TABLE test ( value INTEGER );
INSERT INTO test VALUES (100);
SELECT null, value FROM test
```

#### Steps to reproduce

```
Mono.from(this.connectionFactory.create())
    .flatMapMany(connection -> Flux.from(connection

        .createStatement("SELECT null, value FROM test")
        .execute())
        .flatMap(it -> it.map((row, rowMetadata) -> new Object[]{row.get(0, String.class), row.get(1)}))

        .concatWith(close(connection)))
    .as(StepVerifier::create)
    .consumeNextWith(objects -> {
        System.out.println(Arrays.toString(objects));
    })
    .verifyComplete();
```

#### Expected behavior/code

`Row.get(…)` returns `null`

**Comment by katzyn** [comment]
https://github.com/r2dbc/r2dbc-h2/blob/6abaf05b34417115d4d3bb65c42c02fc06d54988/src/main/java/io/r2dbc/h2/codecs/DefaultCodecs.java#L51-L53

In H2 `value == ValueNull.INSTANCE` is used as a check for SQL NULL value.
