### ISSUE TITLE
Selecting from a table with JSON column is not possible.

### ISSUE THREAD

**Issue by gofabian** [r2dbc/r2dbc-h2#180]
## Bug Report

A `select` from a table with `json` column always results in an exception:

    java.lang.IllegalArgumentException: Cannot decode value of type java.lang.Object

#### Versions

- Driver: r2dbc-h2 0.8.4.RELEASE
- Database: 1.4.200 (from Spring Boot 2.4.1)
- Java: 11
- OS: Windows 10

#### Current Behavior

- Creating a table with json column works. -> ok
- Inserting into the table works. -> ok
- Selecting fails with an exception. -> nok

<details>
<summary>Stack trace</summary>

```
java.lang.IllegalArgumentException: Cannot decode value of type java.lang.Object

	at io.r2dbc.h2.codecs.DefaultCodecs.decode(DefaultCodecs.java:60)
	at io.r2dbc.h2.H2Row.get(H2Row.java:66)
	at io.r2dbc.spi.Row.get(Row.java:51)
	at org.springframework.r2dbc.core.ColumnMapRowMapper.getColumnValue(ColumnMapRowMapper.java:99)
	at org.springframework.r2dbc.core.ColumnMapRowMapper.apply(ColumnMapRowMapper.java:63)
	at org.springframework.r2dbc.core.ColumnMapRowMapper.apply(ColumnMapRowMapper.java:49)
	at io.r2dbc.h2.H2Result.lambda$map$0(H2Result.java:67)
	at reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:106)
	at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onNext(FluxOnErrorResume.java:79)
	at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onNext(FluxMapFuseable.java:127)
	at reactor.core.publisher.FluxIterable$IterableSubscription.slowPath(FluxIterable.java:270)
	at reactor.core.publisher.FluxIterable$IterableSubscription.request(FluxIterable.java:228)
	at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.request(FluxMapFuseable.java:169)
	at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.set(Operators.java:2154)
	at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onSubscribe(FluxOnErrorResume.java:74)
	at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onSubscribe(FluxMapFuseable.java:96)
	at reactor.core.publisher.FluxIterable.subscribe(FluxIterable.java:164)
	at reactor.core.publisher.FluxIterable.subscribe(FluxIterable.java:86)
	at reactor.core.publisher.Flux.subscribe(Flux.java:8147)
	at reactor.core.publisher.FluxFlatMap$FlatMapMain.onNext(FluxFlatMap.java:425)
	at reactor.core.publisher.FluxOnAssembly$OnAssemblySubscriber.onNext(FluxOnAssembly.java:387)
	at reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:120)
	at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onNext(FluxMapFuseable.java:127)
	at reactor.core.publisher.FluxIterable$IterableSubscription.slowPath(FluxIterable.java:270)
	at reactor.core.publisher.FluxIterable$IterableSubscription.request(FluxIterable.java:228)
	at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.request(FluxMapFuseable.java:169)
	at reactor.core.publisher.FluxMap$MapSubscriber.request(FluxMap.java:162)
	at reactor.core.publisher.FluxOnAssembly$OnAssemblySubscriber.request(FluxOnAssembly.java:497)
	at reactor.core.publisher.FluxFlatMap$FlatMapMain.onSubscribe(FluxFlatMap.java:370)
	at reactor.core.publisher.FluxOnAssembly$OnAssemblySubscriber.onSubscribe(FluxOnAssembly.java:481)
	at reactor.core.publisher.FluxMap$MapSubscriber.onSubscribe(FluxMap.java:92)
	at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onSubscribe(FluxMapFuseable.java:96)
	at reactor.core.publisher.FluxIterable.subscribe(FluxIterable.java:164)
	at reactor.core.publisher.FluxIterable.subscribe(FluxIterable.java:86)
	at reactor.core.publisher.Flux.subscribe(Flux.java:8147)
	at reactor.core.publisher.FluxFlatMap.trySubscribeScalarMap(FluxFlatMap.java:199)
	at reactor.core.publisher.FluxFlatMap.subscribeOrReturn(FluxFlatMap.java:92)
	at reactor.core.publisher.Flux.subscribe(Flux.java:8133)
	at reactor.core.publisher.FluxUsingWhen$ResourceSubscriber.onNext(FluxUsingWhen.java:202)
	at reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:120)
	at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onNext(FluxOnErrorResume.java:79)
	at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onNext(FluxOnErrorResume.java:79)
	at reactor.core.publisher.FluxRetry$RetrySubscriber.onNext(FluxRetry.java:86)
	at reactor.core.publisher.FluxPeekFuseable$PeekFuseableSubscriber.onNext(FluxPeekFuseable.java:210)
	at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1784)
	at reactor.core.publisher.MonoFlatMap$FlatMapInner.onNext(MonoFlatMap.java:249)
	at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onNext(FluxOnErrorResume.java:79)
	at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1784)
	at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.drain(MonoIgnoreThen.java:148)
	at reactor.core.publisher.MonoIgnoreThen.subscribe(MonoIgnoreThen.java:56)
	at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:64)
	at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:157)
	at reactor.core.publisher.FluxPeek$PeekSubscriber.onNext(FluxPeek.java:199)
	at reactor.core.publisher.FluxPeek$PeekSubscriber.onNext(FluxPeek.java:199)
	at reactor.pool.AbstractPool$Borrower.deliver(AbstractPool.java:419)
	at reactor.pool.SimpleDequePool.lambda$drainLoop$15(SimpleDequePool.java:391)
	at reactor.core.scheduler.ImmediateScheduler.schedule(ImmediateScheduler.java:51)
	at reactor.pool.SimpleDequePool.drainLoop(SimpleDequePool.java:391)
	at reactor.pool.SimpleDequePool.drain(SimpleDequePool.java:261)
	at reactor.pool.SimpleDequePool.doAcquire(SimpleDequePool.java:256)
	at reactor.pool.AbstractPool$Borrower.request(AbstractPool.java:382)
	at reactor.core.publisher.FluxPeek$PeekSubscriber.request(FluxPeek.java:137)
	at reactor.core.publisher.FluxPeek$PeekSubscriber.request(FluxPeek.java:137)
	at reactor.core.publisher.MonoFlatMap$FlatMapMain.onSubscribe(MonoFlatMap.java:110)
	at reactor.core.publisher.FluxPeek$PeekSubscriber.onSubscribe(FluxPeek.java:170)
	at reactor.core.publisher.FluxPeek$PeekSubscriber.onSubscribe(FluxPeek.java:170)
	at reactor.pool.SimpleDequePool$QueueBorrowerMono.subscribe(SimpleDequePool.java:578)
	at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:64)
	at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:52)
	at reactor.core.publisher.FluxRetry$RetrySubscriber.resubscribe(FluxRetry.java:116)
	at reactor.core.publisher.MonoRetry.subscribeOrReturn(MonoRetry.java:49)
	at reactor.core.publisher.Mono.subscribe(Mono.java:4031)
	at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onError(FluxOnErrorResume.java:103)
	at reactor.core.publisher.MonoFlatMap$FlatMapMain.onError(MonoFlatMap.java:172)
	at reactor.core.publisher.FluxMap$MapSubscriber.onError(FluxMap.java:132)
	at reactor.core.publisher.Operators.error(Operators.java:196)
	at reactor.core.publisher.MonoError.subscribe(MonoError.java:52)
	at reactor.core.publisher.MonoDeferContextual.subscribe(MonoDeferContextual.java:55)
	at reactor.core.publisher.Mono.subscribe(Mono.java:4046)
	at reactor.core.publisher.FluxUsingWhen.subscribe(FluxUsingWhen.java:103)
	at reactor.core.publisher.Flux.subscribe(Flux.java:8147)
	at reactor.core.publisher.Flux.blockFirst(Flux.java:2464)
```

</details>

#### Steps to reproduce

<details>
<summary>Input Code</summary>

Example:

```java
        databaseClient.sql("create table \"tab\" ( \"id\" bigint primary key, \"json\" json )")
                .fetch().rowsUpdated().block();

        int count = databaseClient.sql("insert into \"tab\" (\"id\", \"json\") values ($1, $2)")
                .bind(0, 42)
                .bind(1, "{}")
                .fetch().rowsUpdated().block();
        assertEquals(1, count);

        Map map = databaseClient.sql("select * from \"tab\"").fetch().all().blockFirst(); // throws exception
        System.out.println(map);
```

</details>

#### Expected behavior/code

No exception. I can select from table with `json` column.

#### Possible Solution

`org.h2.value.Value.JSON = 40` exists, but there is no dedicated Codec. The implementation of a `JsonCodec` could solve this issue.

**Comment by lukaseder** [comment]
This implementation works for me: https://github.com/r2dbc/r2dbc-h2/pull/191
