### ISSUE TITLE
Outdated connection URLs

### ISSUE THREAD

**Issue by lukaseder** [r2dbc/r2dbc-h2#188]
#### Versions

- Driver: 0.8.4.RELEASE
- SPI: 0.9.0.M1
- Database: 1.4.200
- Java: openjdk version "11.0.9.1" 2020-11-04
- OS: Microsoft Windows [Version 10.0.19042.867]

#### Current Behavior

This code:

```java
ConnectionFactories.get("r2dbc:h2:file///absolute/file/name");
```

Produces this exception

```
Exception in thread "main" java.lang.IllegalArgumentException: Invalid URL: r2dbc:h2:file///absolute/file/name
	at io.r2dbc.spi.ConnectionUrlParser.validate(ConnectionUrlParser.java:67)
	at io.r2dbc.spi.ConnectionUrlParser.parseQuery(ConnectionUrlParser.java:81)
	at io.r2dbc.spi.ConnectionFactoryOptions.parse(ConnectionFactoryOptions.java:124)
	at io.r2dbc.spi.ConnectionFactories.get(ConnectionFactories.java:130)
	at org.jooq.testscripts.R2DBC.main(R2DBC.java:23)
```

This is either a regression in the SPI (less likely), or a breaking change (more likely), after which the documentation of r2dbc-h2 should be updated:
https://github.com/r2dbc/r2dbc-h2/blob/main/README.adoc

**Comment by lukaseder** [comment]
Related (let me know if you wish for me to open a new bug for this).

This works with the above version configuration, but I doubt it should work:

```java
        ConnectionFactory f = ConnectionFactories.get(
            ConnectionFactoryOptions
                .parse("r2dbc:h2:file://localhost/~/test")
                .mutate()
                .option(ConnectionFactoryOptions.USER, "sa")
                .option(ConnectionFactoryOptions.PASSWORD, "")
                .build()
        );
```

I tried random things until I got some `r2dbc` connection URL to work with the `0.9.0.M1` SPI and the `0.8.4.RELEASE` driver.
