### ISSUE TITLE
Unable to start H2 on Spring Boot 2.6.3

### ISSUE THREAD

**Issue by andreas-trvlk** [r2dbc/r2dbc-h2#224]
#### Versions

- Driver: 0.9.1.RELEASE
- Database: 1.4.200
- Java: 11
- OS: MacOS 12
- Spring Boot: 2.6.3

#### Current Behavior

<details>
<summary>Stack trace</summary>

```
Caused by: java.lang.IllegalArgumentException: Cannot determine database's type as ConnectionFactory is not options-capable. To be options-capable, a ConnectionFactory should be created with org.springframework.boot.r2dbc.ConnectionFactoryBuilder
	at org.springframework.util.Assert.notNull(Assert.java:219)
	at org.springframework.boot.r2dbc.EmbeddedDatabaseConnection.isEmbedded(EmbeddedDatabaseConnection.java:102)
	at org.springframework.boot.r2dbc.init.R2dbcScriptDatabaseInitializer.isEmbeddedDatabase(R2dbcScriptDatabaseInitializer.java:57)
	at org.springframework.boot.sql.init.AbstractScriptDatabaseInitializer.isEnabled(AbstractScriptDatabaseInitializer.java:83)
	at org.springframework.boot.sql.init.AbstractScriptDatabaseInitializer.applyScripts(AbstractScriptDatabaseInitializer.java:106)
	at org.springframework.boot.sql.init.AbstractScriptDatabaseInitializer.applySchemaScripts(AbstractScriptDatabaseInitializer.java:97)
	at org.springframework.boot.sql.init.AbstractScriptDatabaseInitializer.initializeDatabase(AbstractScriptDatabaseInitializer.java:75)

```

</details>
 
#### Table schema

<details>
<summary>Input Code</summary>

```sql
-- your SQL here;
```

</details>

#### Steps to reproduce

<details>
<summary>Input Code</summary>

```java
Profile("test")
@Configuration
@EnableR2dbcRepositories
class ReactiveH2Configuration(
  private val objectMapper: ObjectMapper
) : AbstractR2dbcConfiguration() {

  @Bean
  override fun connectionFactory(): ConnectionFactory {
    return H2ConnectionFactory(
      H2ConnectionConfiguration.builder()
        .inMemory("testdb")
        .option("MODE=PostgreSQL")
        .option("DB_CLOSE_DELAY=-1")
        .build()
    )
  }
}
```

</details>

**Comment by wilkinsona** [comment]
As the error message suggests, to be able to determine the database's type, Spring Boot requires you to create the connection factory using its `org.springframework.boot.r2dbc.ConnectionFactoryBuilder`. You haven't done so and as a result the database's type cannot be determined.
