### ISSUE TITLE
StackOverflowException when attempting to decode Geometry

### ISSUE THREAD

**Issue by geirsagberg** [r2dbc/r2dbc-h2#240]
#### Versions

- Driver: 1.0.0.RELEASE
- Database: 2.1.214
- Java: 17
- OS: macOS 13.3.1

#### Current Behavior

When attempting to decode a GEOMETRY column without specifying class, there is an infinite loop:

<details>
<summary>Stack trace</summary>

```
Codec.doDecode(ParameterCodec.java:6) ~[r2dbc-h2-1.0.0.RELEASE.jar:1.0.0.RELEASE]
	at io.r2dbc.h2.codecs.AbstractCodec.decode(AbstractCodec.java:60) ~[r2dbc-h2-1.0.0.RELEASE.jar:1.0.0.RELEASE]
	at io.r2dbc.h2.codecs.DefaultCodecs.decode(DefaultCodecs.java:57) ~[r2dbc-h2-1.0.0.RELEASE.jar:1.0.0.RELEASE]
	at io.r2dbc.h2.codecs.ParameterCodec.doDecode(ParameterCodec.java:22) ~[r2dbc-h2-1.0.0.RELEASE.jar:1.0.0.RELEASE]
	at io.r2dbc.h2.codecs.ParameterCodec.doDecode(ParameterCodec.java:6) ~[r2dbc-h2-1.0.0.RELEASE.jar:1.0.0.RELEASE]
	at io.r2dbc.h2.codecs.AbstractCodec.decode(AbstractCodec.java:60) ~[r2dbc-h2-1.0.0.RELEASE.jar:1.0.0.RELEASE]
	at io.r2dbc.h2.codecs.DefaultCodecs.decode(DefaultCodecs.java:57) ~[r2dbc-h2-1.0.0.RELEASE.jar:1.0.0.RELEASE]
	at io.r2dbc.h2.codecs.ParameterCodec.doDecode(ParameterCodec.java:22) ~[r2dbc-h2-1.0.0.RELEASE.jar:1.0.0.RELEASE]
	at io.r2dbc.h2.codecs.ParameterCodec.doDecode(ParameterCodec.java:6) ~[r2dbc-h2-1.0.0.RELEASE.jar:1.0.0.RELEASE]
	at io.r2dbc.h2.codecs.AbstractCodec.decode(AbstractCodec.java:60) ~[r2dbc-h2-1.0.0.RELEASE.jar:1.0.0.RELEASE]
	at io.r2dbc.h2.codecs.DefaultCodecs.decode(DefaultCodecs.java:57) ~[r2dbc-h2-1.0.0.RELEASE.jar:1.0.0.RELEASE]
	at io.r2dbc.h2.codecs.ParameterCodec.doDecode(ParameterCodec.java:22) ~[r2dbc-h2-1.0.0.RELEASE.jar:1.0.0.RELEASE]
	at io.r2dbc.h2.codecs.ParameterCodec.doDecode(ParameterCodec.java:6) ~[r2dbc-h2-1.0.0.RELEASE.jar:1.0.0.RELEASE]
```

</details>
 
#### Table schema

<details>
<summary>Input Code</summary>

```sql
CREATE TABLE IF NOT EXISTS geometric
(
    if       LONG PRIMARY KEY,
    geometry GEOMETRY
);
```

</details>

#### Steps to reproduce

[This repo](https://github.com/geirsagberg/spring-data-r2dbc-geometry-bug) reproduces the problem via Spring Data.
[This fork and commit adds a test and a fix](https://github.com/r2dbc/r2dbc-h2/compare/main...geirsagberg:r2dbc-h2:main)

#### Expected behavior/code

It should be possible to decode GEOMETRY without sending in the Class.

#### Possible Solution

[This fork and commit adds a test and a fix](https://github.com/r2dbc/r2dbc-h2/compare/main...geirsagberg:r2dbc-h2:main)

**Comment by petercooperjr-spls** [comment]
I'm running into this as well; is the release with this fix in it published somewhere?
