### ISSUE TITLE
Fix select bind incompatibility with H2 1.4.198

### ISSUE THREAD

**Issue by pacphi** [r2dbc/r2dbc-h2#51]
Using `r2dbc-h2-1.0.0.M7` I see that select bindings fail with

```
java.lang.NoSuchMethodError: org.h2.result.ResultInterface.getColumnType(I)I
    at io.r2dbc.h2.H2ColumnMetadata.toColumnMetadata(H2ColumnMetadata.java:127) ~[r2dbc-h2-1.0.0.M7.jar:na]
    at io.r2dbc.h2.H2RowMetadata.getColumnMetadatas(H2RowMetadata.java:106) ~[r2dbc-h2-1.0.0.M7.jar:na]
    at io.r2dbc.h2.H2RowMetadata.toRowMetadata(H2RowMetadata.java:99) ~[r2dbc-h2-1.0.0.M7.jar:na]
    at io.r2dbc.h2.H2Result.toResult(H2Result.java:86) ~[r2dbc-h2-1.0.0.M7.jar:na]
```

**Comment by sdeleuze** [comment]
Same issue with Boot 2.2 + r2dbc-h2 1.0.0.M6 which is using H2 1.4.198 by default.

**Comment by mp911de** [comment]
See also https://github.com/r2dbc/r2dbc-h2/issues/9#issuecomment-471470177.

After discussing with H2 folks, the only stable H2 API is JDBC and H2 internals (used by r2dbc-h2) are always subject to change. So the best effort we can make is keeping up with H2 changes.
