### ISSUE TITLE
Binary field data auto converting to null binding when using ReactiveCrudRepository.

### ISSUE THREAD

**Issue by gm2552** [r2dbc/r2dbc-h2#79]
When creating a table with a BLOB and a supporting entity class coupled with a ReactiveCrudRepository interface, the byte[] field will not save to the database.  The resulting error is:  java.lang.IllegalArgumentException: Cannot encode null parameter of type [Ljava.lang.Byte;)

Tracing into a unit test, the type of the binary field in converted to java.lang.Byte[], but the codec is looking for byte[]  (i.e. type [b).

I've provided a simple project that can recreate the issue with a simple unit test.  

https://github.com/gm2552/r2dbc-binarydata-sample.git

**Comment by gregturn** [comment]
I think something may be askew in the Spring Data R2dbc layer, perhaps where it's declared a `BLOB`.

Debugging your repo again latest changes shows that `NULL` is getting passed into `r2dbc-h2`. And for that, H2 is failing properly, considering the **CERT** column is marked **NOT NULL**.

@mp911de perhaps you could help decode what is happening in that layer so we could pass a proper byte array down?

**Comment by mp911de** [comment]
Binary data isn’t required to be always a blob. So using byte[] should be possible with R2DBC drivers  Blobs focus more on the large object part supporting character and binary data. Also, I would not recommend handing out a Blob object into a mapped pojo because blobs are typically associated with a transaction/connection. 

Does this help?

**Comment by gregturn** [comment]
The test code in the linked repo...

```java
final Provider prov1 = new Provider(null, "First1", "Last1", new byte[]{1, 2, 3, 4, 5});
final Provider prov2 = new Provider(null, "First2", "Last2", new byte[]{6, 7, 8, 9, 0});
```

...shows a byte array, yet in my debugger, `r2dbc-h2` is getting handed a `null`.

Smells like something in the translation layer is going wrong.

**Comment by gregturn** [comment]
Stack track looks like:

```java
	Suppressed: java.lang.IllegalArgumentException: Cannot encode null parameter of type [Ljava.lang.Byte;
		at io.r2dbc.h2.codecs.DefaultCodecs.encodeNull(DefaultCodecs.java:100)
		at io.r2dbc.h2.H2Statement.bindNull(H2Statement.java:109)
		at io.r2dbc.h2.H2Statement.bindNull(H2Statement.java:36)
		at org.springframework.data.r2dbc.core.DefaultDatabaseClient$StatementWrapper.bindNull(DefaultDatabaseClient.java:1479)
		at org.springframework.data.r2dbc.dialect.IndexedBindMarker.bindNull(IndexedBindMarker.java:56)
		at org.springframework.data.r2dbc.dialect.Bindings$NullBinding.apply(Bindings.java:281)
		at org.springframework.data.r2dbc.dialect.Bindings.lambda$apply$1(Bindings.java:122)
		at java.util.LinkedHashMap.forEach(LinkedHashMap.java:684)
		at org.springframework.data.r2dbc.dialect.Bindings.apply(Bindings.java:122)
		at org.springframework.data.r2dbc.core.DefaultStatementMapper$DefaultPreparedOperation.bindTo(DefaultStatementMapper.java:330)
		at org.springframework.data.r2dbc.core.DefaultDatabaseClient.lambda$wrapPreparedOperation$14(DefaultDatabaseClient.java:1329)
		at java.util.function.Function.lambda$andThen$1(Function.java:88)
		at org.springframework.data.r2dbc.core.DefaultDatabaseClient.lambda$exchangeInsert$9(DefaultDatabaseClient.java:1291)
		at org.springframework.data.r2dbc.core.DefaultSqlResult$2.apply(DefaultSqlResult.java:80)
		at org.springframework.data.r2dbc.core.DefaultSqlResult$2.apply(DefaultSqlResult.java:77)
		at org.springframework.data.r2dbc.core.DefaultDatabaseClient.doInConnectionMany(DefaultDatabaseClient.java:1338)
		at org.springframework.data.r2dbc.core.DefaultDatabaseClient.lambda$inConnectionMany$4(DefaultDatabaseClient.java:178)
		at reactor.core.publisher.FluxUsingWhen.deriveFluxFromResource(FluxUsingWhen.java:117)
		at reactor.core.publisher.FluxUsingWhen.access$000(FluxUsingWhen.java:52)
		at reactor.core.publisher.FluxUsingWhen$ResourceSubscriber.onNext(FluxUsingWhen.java:193)
```

Why is Spring Data R2dbc attempting to do a `bindNull` given the argument is not null?

**Comment by mp911de** [comment]
Closing in favor of spring-projects/spring-data-r2dbc#186.

**Comment by gm2552** [comment]
With the latest updates from https://github.com/spring-projects/spring-data-r2dbc/issues/186, the problem is now manifest directly in the driver.  Opening a new issue to demonstrate the driver issue (actually is present in several vendor specific driver; will open a separate issue in the appropriate repositories for each).

**Comment by mp911de** [comment]
How so? Can you provide more details on what is broken with which driver?

**Comment by gm2552** [comment]
Yep... I'm working on getting a new issue filed as I type along with an updated sample to reproduce the issue.
